#! /usr/bin/env python
list = Split("""
lineportion.c
""")

Import('env');

termbuffer = env.Library(
    'termbuffer'
    , list
    , CPPPATH = ['/usr/include/glib-2.0', '/usr/lib/glib-2.0/include']
    , LIBS = ['glib-2.0', 'util']);

