#! /usr/bin/env python
list = Split("""
lineportion.c
""")

include = Split("""
/usr/include/glib-2.0
/usr/lib/glib-2.0/include
../terminfo
../debug
""")

Import('env');

termbuffer = env.Library(
    'termbuffer'
    , list
    , CPPPATH = include);

