#! /usr/bin/env python

##env = Environment(CC = 'gcc', CCFLAGS = '-march=i386 -ggdb -Wall')
#env = Environment(CC = 'gcc', CCFLAGS = '-march=i386 -ggdb -DDEBUG -Wall')
env = Environment(CC = 'gcc', CCFLAGS = '-march=i386 -O2 -Wall')

Export('env')

SConscript(['src/SConscript'], build_dir='build')
