#! /usr/bin/env python

env = Environment(CC = 'gcc'
                  , CCFLAGS = '-march=i386 -g -DDEBUG -Wall')

#env = Environment(CC = 'gcc', CCFLAGS = '-O2 -fPIC -Wall')

Export('env')

SConscript(['src/SConscript'], build_dir='build')
