#! /usr/bin/env python
list = Split("""
links2vox.c
""")

include = Split("""
/usr/include/glib-2.0
/usr/lib/glib-2.0/include
../document
../graphic
../speech
../mode
../plugin
../termapi
../termbuffer
../terminfo
../debug
""")

Import('env');


links2vox = env.SharedLibrary(
    'links2vox'
    , list
    , CPPPATH = include
    , LINKFLAGS = "-Wl,--soname=liblinks2vox.so.1"
    );

InstallAs("liblinks2vox.so.1.0.0", links2vox)
