#! /usr/bin/env python
list = Split("""
escape2terminfo.c
linuxconsole.c	
terminfo2list.c
terminfointerpreter.c  
tifilter2l.c
""")

Import('env');

env.CXXFile( "escape2terminfo.c", "escape2terminfo.ll" )

terminfo = env.Library(
    'terminfo'
    , list
    , CPPPATH = ['/usr/include/glib-2.0'
                 , '/usr/lib/glib-2.0/include'
                 ,'.'
                 ,'../termbuffer'
                 ,'../termapi'
                 ,'../debug']
    , LIBS = ['glib-2.0', 'util']);

