#! /usr/bin/env python

Import('env')

env.SConscript('graphic/SConscript')
env.SConscript('plugin/SConscript')
env.SConscript('termapi/SConscript')
env.SConscript('termbuffer/SConscript')
env.SConscript('terminfo/SConscript')
env.SConscript('debug/SConscript')
env.SConscript('mode/SConscript')
env.SConscript('document/SConscript')
env.SConscript('main/SConscript')
