#! /usr/bin/env python
list = Split("""
test-tengoo.c
""")

include = Split("""
/usr/include/glib-2.0
/usr/lib/glib-2.0/include
../termbuffer
""")

Import('env')

env.Program(target = 'tengoo'
            , source = list
            , CPPPATH = include
            , LIBPATH = ['../termapi',
                         '../termbuffer',
                         '../terminfo',
                         '../debug']
            , LIBS = ['glib-2.0',
                      'util',
                      'termapi',
                      'termbuffer',
                      'terminfo',
                      'debug'])
