#! /usr/bin/env python
list = Split("""
tengoo.c
test-tengoo.c
""")

include = Split("""
/usr/include/glib-2.0
/usr/lib/glib-2.0/include
../graphic
../mode
../plugin
../termbuffer
../termapi
../terminfo
../debug
""")

Import('env')

tengoo = env.Library(target = 'tengoo'
                     , source = 'tengoo.c'
                     , CPPPATH = include
                     , LIBPATH = ['../document',
                                  '../graphic',
                                  '../mode',
                                  '../plugin',
                                  '../termapi',
                                  '../termbuffer',
                                  '../terminfo',
                                  '../debug']
                     , LIBS = ['gmodule-2.0',
                               'glib-2.0',
                               'links2vox',
                               'document',
                               'graphic',
                               'mode',
                               'util',
                               'termapi',
                               'terminfo',
                               'termbuffer',
                               'debug']);

env.Program(target = 'test-tengoo'
            , source = 'test-tengoo.c'
            , CPPPATH = include
            , LIBPATH = ['.',
                         '../document',
                         '../graphic',
                         '../mode',
                         '../plugin',
                         '../termapi',
                         '../termbuffer',
                         '../terminfo',
                         '../debug']
            , LIBS = ['gmodule-2.0',
                      'glib-2.0',
                      'tengoo',
                      'links2vox',
                      'document',
                      'graphic',
                      'mode',
                      'util',
                      'termapi',
                      'terminfo',
                      'termbuffer',
                      'debug']);

