#! /usr/bin/env python
list = Split("""
tengoo.c
test-tengoo.c
""")

include = Split("""
/usr/include/glib-2.0
/usr/lib/glib-2.0/include
../graphic
../mode
../plugin
../termbuffer
../termapi
../terminfo
../debug
""")

Import('env')

env.Program(target = 'tengoo'
            , source = list
            , CPPPATH = include
            , LIBPATH = ['../graphic',
                         '../mode',
                         '../plugin',
                         '../termapi',
                         '../termbuffer',
                         '../terminfo',
                         '../debug']
            , LIBS = ['gmodule-2.0',
                      'glib-2.0',
                      'links2vox',
                      'graphic',
                      'mode',
                      'util',
                      'termapi',
                      'termbuffer',
                      'terminfo',
                      'debug'])
