#! /usr/bin/env python
list = Split("""
linuxscreen.c
linuxscreen.h
termapi.h
termapiVCSA.c
""")

include = Split("""
/usr/include/glib-2.0
/usr/lib/glib-2.0/include
""")

Import('env')

termapi = env.Library(
    'termapi'
    , list
    , CPPPATH = ['../debug', '../terminfo', '../termbuffer','/usr/include/glib-2.0', '/usr/lib/glib-2.0/include'])
