#! /usr/bin/env python
list = Split("""
docAPI.c
frame.c
""")

include = Split("""
/usr/include/glib-2.0
/usr/lib/glib-2.0/include
../graphic
../terminfo
../termbuffer
../debug
""")

Import('env');

termbuffer = env.Library(
    'document'
    , list
    , CPPPATH = include);

