#! /usr/bin/env python
list = Split("""
action.c
modeAPI.c
""")

include = Split("""
/usr/include/glib-2.0
/usr/lib/glib-2.0/include
../document
../graphic
../mode
../plugin
../termapi
../termbuffer
../terminfo
../debug
""")

Import('env');

mode = env.Library(
    'mode'
    , list
    , CPPPATH = include);

