#! /usr/bin/env python
list = Split("""
action.c
mode.c
""")

include = Split("""
/usr/include/glib-2.0
/usr/lib/glib-2.0/include
../termapi
../termbuffer
../terminfo
../debug
""")

Import('env');

termbuffer = env.Library(
    'mode'
    , list
    , CPPPATH = include);

