( cd usr/share/emacs/site-lisp/emacspeak/lisp ; rm -rf Russian-spelling.el )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; ln -sf /usr/local/lib/multispeech/lisp/Russian-spelling.el Russian-spelling.el )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; rm -rf mbrola-css-speech.el )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; ln -sf /usr/local/lib/multispeech/lisp/mbrola-css-speech.el mbrola-css-speech.el )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; rm -rf mbrola-css-speech.elc )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; ln -sf /usr/local/lib/multispeech/lisp/mbrola-css-speech.elc mbrola-css-speech.elc )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; rm -rf mbrola-voices.el )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; ln -sf /usr/local/lib/multispeech/lisp/mbrola-voices.el mbrola-voices.el )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; rm -rf mbrola-voices.elc )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; ln -sf /usr/local/lib/multispeech/lisp/mbrola-voices.elc mbrola-voices.elc )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; rm -rf multilingual-server.el )
( cd usr/share/emacs/site-lisp/emacspeak/lisp ; ln -sf /usr/local/lib/multispeech/lisp/multilingual-server.el multilingual-server.el )
